export type EnvKeys = {
    CLOUD_PROVIDER: true,

    DATABASE_TYPE: true,
    DATABASE_FILENAME: true,
    DATABASE_HOST: true,
    DATABASE_PORT: true,
    DATABASE_NAME: true,
    DATABASE_USERNAME: true,
    DATABASE_PASSWORD: true,
    DATABASE_SSL: true,
    DATABASE_SSL_KEY: true,
    DATABASE_SSL_CERT: true,
    DATABASE_SSL_CA: true,
    DATABASE_SSL_CAPATH: true,
    DATABASE_SSL_CIPHER: true,
    DATABASE_SSL_REJECT_UNAUTHORIZED: true,
    DATABASE_POOL_MAX: true,
    DATABASE_CONNECTION_TIMEOUT: true,
    DATABASE_URL: true,
    DATABASE_SCHEMA: true,

    IDENTITY_ACCESS_TOKEN_EXPIRATION: true,
    IDENTITY_REFRESH_TOPKEN_EXPIRATION: true,
    IDENTITY_PRIVATE_KEY: true,

    HUBJECT_PROXY_BASE_URL: true,
    HUBJECT_PROXY_API_KEY: true,
    HUBJECT_PROXY_ROUTE_KEY: true,
    HUBJECT_PROVIDER_ID: true,

    SAAS_CHARGE_AUTH_TOKEN: true,
    SAAS_CHARGE_BASE_URL: true,
    SAAS_CHARGE_SOAP_URL: true,
    SAAS_CHARGE_SOCKET_BASE_URL: true,
    SAAS_LOCATION_CSO_NAME: true,
    SAAS_VCG_EMPID: true,
    SAAS_VCG_INTERNAL_CLIENT_NUMBER: true,
    SAAS_VCG_PRICE_PLAN_NAME: true,

    STRIPE_KEY: true,
    STRIPE_WEBHOOK_SECRET: true
    PRICE_BUFFER_PERCENTAGE: true

    ASSETS_BUCKET_KEY: true,
    ASSETS_BUCKET_NAME: true,

    LOCATION_INDEX_NAME: true,

    DEV_APP_ID: true,
    DEV_MEMBER_ID: true,
    DEV_CUSTOMER_ID: true,
    DEV_IDENTITY: true,

    CDR_MISSED_SESSIONS_THRESHOLD: true,

    SENDGRID_API_KEY: true,
    SENDGRID_DEFAULT_SENDER: true,
    SENDGRID_WELCOME_TEMPLATE_ID: true,
    SENDGRID_INVOICE_TEMPLATE_ID: true,

    // not used ...
    LEG_SENTRY_DSN: true,
    LOG_LEVEL: true,
    SENTRY_ENVIRONMENT: true,
    SENTRY_RELEASE: true,
}